(define (problem minecraft-diamond-pickaxe)
    (:domain minecraft-blocks)

    (:objects
        agent01 - agent
        wood01 wood02 wood03 wood04 wood05 wood06 wood07 wood08 wood09 wood10 wood11 wood12 wood13 wood14 wood15 wood16 wood17 wood18 wood19 wood20 - wood  
        stone01 stone02 stone03 stone04 stone05 stone06 stone07 stone08 stone09 stone10 stone11 stone12 stone13 stone14 stone15 stone16 stone17 stone18 stone19 stone20 - stone
        iron01 iron02 iron03 iron04 iron05 iron06 iron07 iron08 iron09 iron10 iron11 iron12 iron13 iron14 iron15 iron16 iron17 iron18 iron19 iron20 - iron
        gold01 gold02 gold03 gold04 gold05 gold06 gold07 gold08 gold09 gold10 gold11 gold12 gold13 gold14 gold15 gold16 gold17 gold18 gold19 gold20 - gold
        diamond01 diamond02 diamond03 diamond04 diamond05 diamond06 diamond07 diamond08 diamond09 diamond10 diamond11 diamond12 diamond13 diamond14 diamond15 diamond16 diamond17 diamond18 diamond19 diamond20 - diamond  
    )

    (:init
        (alive agent01)
        (wood_not_collected wood01)
        (wood_not_collected wood02)
        (wood_not_collected wood03)
        (wood_not_collected wood04)
        (wood_not_collected wood05)
        (wood_not_collected wood06)
        (wood_not_collected wood07)
        (wood_not_collected wood08)
        (wood_not_collected wood09)
        (wood_not_collected wood10)
        (wood_not_collected wood11)
        (wood_not_collected wood12)
        (wood_not_collected wood13)
        (wood_not_collected wood14)
        (wood_not_collected wood15)
        (wood_not_collected wood16)
        (wood_not_collected wood17)
        (wood_not_collected wood18)
        (wood_not_collected wood19)
        (wood_not_collected wood20)
        (stone_not_collected stone01)
        (stone_not_collected stone02)
        (stone_not_collected stone03)
        (stone_not_collected stone04)
        (stone_not_collected stone05)
        (stone_not_collected stone06)
        (stone_not_collected stone07)
        (stone_not_collected stone08)
        (stone_not_collected stone09)
        (stone_not_collected stone10)
        (stone_not_collected stone11)
        (stone_not_collected stone12)
        (stone_not_collected stone13)
        (stone_not_collected stone14)
        (stone_not_collected stone15)
        (stone_not_collected stone16)
        (stone_not_collected stone17)
        (stone_not_collected stone18)
        (stone_not_collected stone19)
        (stone_not_collected stone20)
        (iron_not_collected iron01)
        (iron_not_collected iron02)
        (iron_not_collected iron03)
        (iron_not_collected iron04)
        (iron_not_collected iron05)
        (iron_not_collected iron06)
        (iron_not_collected iron07)
        (iron_not_collected iron08)
        (iron_not_collected iron09)
        (iron_not_collected iron10)
        (iron_not_collected iron11)
        (iron_not_collected iron12)
        (iron_not_collected iron13)
        (iron_not_collected iron14)
        (iron_not_collected iron15)
        (iron_not_collected iron16)
        (iron_not_collected iron17)
        (iron_not_collected iron18)
        (iron_not_collected iron19)
        (iron_not_collected iron20)
        (gold_not_collected gold01)
        (gold_not_collected gold02)
        (gold_not_collected gold03)
        (gold_not_collected gold04)
        (gold_not_collected gold05)
        (gold_not_collected gold06)
        (gold_not_collected gold07)
        (gold_not_collected gold08)
        (gold_not_collected gold09)
        (gold_not_collected gold10)
        (gold_not_collected gold11)
        (gold_not_collected gold12)
        (gold_not_collected gold13)
        (gold_not_collected gold14)
        (gold_not_collected gold15)
        (gold_not_collected gold16)
        (gold_not_collected gold17)
        (gold_not_collected gold18)
        (gold_not_collected gold19)
        (gold_not_collected gold20)
        (diamond_not_collected diamond01)
        (diamond_not_collected diamond02)
        (diamond_not_collected diamond03)
        (diamond_not_collected diamond04)
        (diamond_not_collected diamond05)
        (diamond_not_collected diamond06)
        (diamond_not_collected diamond07)
        (diamond_not_collected diamond08)
        (diamond_not_collected diamond09)
        (diamond_not_collected diamond10)
        (diamond_not_collected diamond11)
        (diamond_not_collected diamond12)
        (diamond_not_collected diamond13)
        (diamond_not_collected diamond14)
        (diamond_not_collected diamond15)
        (diamond_not_collected diamond16)
        (diamond_not_collected diamond17)
        (diamond_not_collected diamond18)
        (diamond_not_collected diamond19)
        (diamond_not_collected diamond20)
    )

    (:goal (and
        (has_wood_pickaxe agent01)
    ))

)